### ISSUE TITLE
异常错误，显示内存不足

### ISSUE THREAD

**Issue by Aisakaguya** [NaughtDZ/Image2Pdf_2.0#1]
![5e2391b4fd4da06318cebbbff3462c2](https://github.com/NaughtDZ/Image2Pdf_2.0/assets/117366286/4dca8975-1bdb-45f3-b9c9-3627b2cd1f65)
![704b550e293f82cb2b25a3afe224681](https://github.com/NaughtDZ/Image2Pdf_2.0/assets/117366286/0dcf6889-52ca-4988-a29f-aba064284a60)

**Comment by NaughtDZ** [comment]
请问一下你准备转换成pdf文件的那个目录的漫画总共大小是多少？

**Comment by NaughtDZ** [comment]
周末我闲下来看看能不能用pdfsharp里有个边写边保存到磁盘的一个方法来优化下，但是代价就是硬盘io变多

**Comment by NaughtDZ** [comment]
试试新版本：
https://github.com/NaughtDZ/Image2Pdf_2.0/releases/tag/Release
但是还是不能根治，我理想中的应该是程序跑起来大概就占那么几兆的空间，然后所有操作全走硬盘。还是水平不到位哈。

**Comment by Aisakaguya** [comment]
> 请问一下你准备转换成pdf文件的那个目录的漫画总共大小是多少？

大概是600m左右，不过我用来转本子没啥问题，但是用来转漫画就会报错

**Comment by Aisakaguya** [comment]
> 试试新版本： https://github.com/NaughtDZ/Image2Pdf_2.0/releases/tag/Release 但是还是不能根治，我理想中的应该是程序跑起来大概就占那么几兆的空间，然后所有操作全走硬盘。还是水平不到位哈。

大佬幸苦了，我之前都是用照片的打印选项转化成pdf文件，但是没法批量操作，这个项目是真是帮大忙了qwq

**Comment by Aisakaguya** [comment]
> 试试新版本： https://github.com/NaughtDZ/Image2Pdf_2.0/releases/tag/Release 但是还是不能根治，我理想中的应该是程序跑起来大概就占那么几兆的空间，然后所有操作全走硬盘。还是水平不到位哈。

![UEMX`HIG{ 3WD5S2 X~H0 V](https://github.com/NaughtDZ/Image2Pdf_2.0/assets/117366286/69a7a2a5-b817-4df3-89de-9b46f42529e3)
新版本出现了新问题O.O

**Comment by NaughtDZ** [comment]
> > 试试新版本： https://github.com/NaughtDZ/Image2Pdf_2.0/releases/tag/Release 但是还是不能根治，我理想中的应该是程序跑起来大概就占那么几兆的空间，然后所有操作全走硬盘。还是水平不到位哈。
> 
> ![UEMX`HIG{ 3WD5S2 X~H0 V](https://user-images.githubusercontent.com/117366286/277162433-69a7a2a5-b817-4df3-89de-9b46f42529e3.png) 新版本出现了新问题O.O

朋友，你有设置输出文件路径吗？

**Comment by NaughtDZ** [comment]
> > 试试新版本： https://github.com/NaughtDZ/Image2Pdf_2.0/releases/tag/Release 但是还是不能根治，我理想中的应该是程序跑起来大概就占那么几兆的空间，然后所有操作全走硬盘。还是水平不到位哈。
> 
> ![UEMX`HIG{ 3WD5S2 X~H0 V](https://user-images.githubusercontent.com/117366286/277162433-69a7a2a5-b817-4df3-89de-9b46f42529e3.png) 新版本出现了新问题O.O

![image](https://github.com/NaughtDZ/Image2Pdf_2.0/assets/37768911/f0ad5eae-5786-42ff-bfc6-dce2d26a19e7)
方便像这样截一下你要转换的目录结构吗？我自己试了下没啥问题，图片里参杂其他奇怪的格式也不会有问题。

**Comment by Aisakaguya** [comment]
![SXCGU~7`0NCRMJIF13U@57H](https://github.com/NaughtDZ/Image2Pdf_2.0/assets/117366286/b3a3828d-0a7f-4b15-803a-e1b06bae36ea)

**Comment by NaughtDZ** [comment]
> ![SXCGU~7`0NCRMJIF13U@57H](https://user-images.githubusercontent.com/117366286/277330904-b3a3828d-0a7f-4b15-803a-e1b06bae36ea.png)

额，你转别的漫画能成功吗？我这里完全无法复现你发生的问题。

**Comment by Aisakaguya** [comment]
这个漫画文件夹下的所有漫画都转不了

**Comment by NaughtDZ** [comment]
> 这个漫画文件夹下的所有漫画都转不了

这.....我没法解释了，太神奇了。我用了我们单位的老win7，win10，自己的win11笔记本，然后各种稀奇古怪的文件夹名字，文件名，都没有报错。。。。这也太怪了。如果方便的话，你能不能打包一个你要转的漫画，百度网盘分享给我，我转下看看。

**Comment by Aisakaguya** [comment]
链接：https://pan.baidu.com/s/1CuSF9-76GX5akofeNrlnkA 
提取码：pu6z 
--来自百度网盘超级会员V2的分享

**Comment by Aisakaguya** [comment]
[报错详细信息.txt](https://github.com/NaughtDZ/Image2Pdf_2.0/files/13114828/default.txt)

**Comment by NaughtDZ** [comment]
> [报错详细信息.txt](https://github.com/NaughtDZ/Image2Pdf_2.0/files/13114828/default.txt)

先说下那个参数错误的问题，你这图片表面上扩展名是png,实际上是webp编码的图，pdfsharp目测不支持这个格式。
你给我发的这个报错是内存不足的报错。
综上，我觉得这个项目我要重新找个pdf的轮子，或者干脆自己重新造轮子了。

**Comment by Aisakaguya** [comment]
> > [报错详细信息.txt](https://github.com/NaughtDZ/Image2Pdf_2.0/files/13114828/default.txt)
> 
> 先说下那个参数错误的问题，你这图片表面上扩展名是png,实际上是webp编码的图，pdfsharp目测不支持这个格式。 你给我发的这个报错是内存不足的报错。 综上，我觉得这个项目我要重新找个pdf的轮子，或者干脆自己重新造轮子了。

辛苦大佬了O.O

**Comment by NaughtDZ** [comment]
很讨厌的是，我转了一圈也没发现有开源的库支持webp，谷歌你做的好啊。
![image](https://github.com/NaughtDZ/Image2Pdf_2.0/assets/37768911/10287821-3f9d-43b3-a077-00dc0a61ff6a)
那么就得每个文件挨个读文件头来判断webp，但是我实际上根本不准备支持webp，因为从你的webp编码图片到pdf，必定要经过一道判断+转换（手动让用户选择会有两个问题，一个是你这种披着png扩展名的webp图，和webp与其他格式混叠，这种预处理是得不偿失的）......所以我现在有两个选择，放弃小而美，扩展一个webp格式转换工具到这个软件里，或者牺牲性能傻瓜式，每张图片都自动判断并转换，或者脱裤子放屁重新造轮子，另开一个webp格式转换工具。。。你说哪个好呢？

**Comment by NaughtDZ** [comment]
https://github.com/NaughtDZ/Image2Pdf_2.0/releases/tag/2.2
船新版本，是兄弟就来砍我。

**Comment by Aisakaguya** [comment]
> 很讨厌的是，我转了一圈也没发现有开源的库支持webp，谷歌你做的好啊。 ![image](https://user-images.githubusercontent.com/37768911/277711861-10287821-3f9d-43b3-a077-00dc0a61ff6a.png) 那么就得每个文件挨个读文件头来判断webp，但是我实际上根本不准备支持webp，因为从你的webp编码图片到pdf，必定要经过一道判断+转换（手动让用户选择会有两个问题，一个是你这种披着png扩展名的webp图，和webp与其他格式混叠，这种预处理是得不偿失的）......所以我现在有两个选择，放弃小而美，扩展一个webp格式转换工具到这个软件里，或者牺牲性能傻瓜式，每张图片都自动判断并转换，或者脱裤子放屁重新造轮子，另开一个webp格式转换工具。。。你说哪个好呢？

转本子是主要应用场景，转webp格式的漫画应用不多，因此我认为另开转换工具是比较好的选择。

**Comment by Aisakaguya** [comment]
> https://github.com/NaughtDZ/Image2Pdf_2.0/releases/tag/2.2 船新版本，是兄弟就来砍我。

![J2M25TU0)U__Z9 F4SAMCWU](https://github.com/NaughtDZ/Image2Pdf_2.0/assets/117366286/58d3223c-96d0-414a-98dd-3272d4f191ba)
浏览器报毒下载不了 (OnO)

**Comment by NaughtDZ** [comment]
> > https://github.com/NaughtDZ/Image2Pdf_2.0/releases/tag/2.2 船新版本，是兄弟就来砍我。
> 
> ![J2M25TU0)U__Z9 F4SAMCWU](https://user-images.githubusercontent.com/117366286/278010242-58d3223c-96d0-414a-98dd-3272d4f191ba.png) 浏览器报毒下载不了 (OnO)

啊我裂开，我就是换了个单文件打包的工具，等会啊，我重新上传一个
还有啊，这啥浏览器，那么敏感？加密打包的单文件就说有病毒？

**Comment by NaughtDZ** [comment]
> > https://github.com/NaughtDZ/Image2Pdf_2.0/releases/tag/2.2 船新版本，是兄弟就来砍我。
> 
> ![J2M25TU0)U__Z9 F4SAMCWU](https://user-images.githubusercontent.com/117366286/278010242-58d3223c-96d0-414a-98dd-3272d4f191ba.png) 浏览器报毒下载不了 (OnO)

https://github.com/NaughtDZ/Image2Pdf_2.0/releases/tag/2.2
已经换了一个打包工具，原则上应该不会报毒(我用的edge)。或者说我的写本地文件策略让你浏览器过于敏感了？反正代码是开源的，不放心就看看源代码或者自己搞个vs构建一下咯。

**Comment by NaughtDZ** [comment]
![image](https://github.com/NaughtDZ/Image2Pdf_2.0/assets/37768911/5303743a-a8bf-4dab-92c4-c06141372775)
![image](https://github.com/NaughtDZ/Image2Pdf_2.0/assets/37768911/96745e19-4b00-4943-9be9-072f1b2da41c)
![image](https://github.com/NaughtDZ/Image2Pdf_2.0/assets/37768911/cbed3ceb-2fd2-480b-a2a7-ac9891cd09b5)
反正我也不知道我哪地方八字犯冲了，有几个引擎扫出来问题，但是报毒都不一样，笑死。
实在不行你就下releases里的rar解压用
![image](https://github.com/NaughtDZ/Image2Pdf_2.0/assets/37768911/d0a79068-b540-4f16-9378-75d759e941d5)

**Comment by Aisakaguya** [comment]
> > > https://github.com/NaughtDZ/Image2Pdf_2.0/releases/tag/2.2 船新版本，是兄弟就来砍我。
> > 
> > 
> > ![J2M25TU0)U__Z9 F4SAMCWU](https://user-images.githubusercontent.com/117366286/278010242-58d3223c-96d0-414a-98dd-3272d4f191ba.png) 浏览器报毒下载不了 (OnO)
> 
> https://github.com/NaughtDZ/Image2Pdf_2.0/releases/tag/2.2 已经换了一个打包工具，原则上应该不会报毒(我用的edge)。或者说我的写本地文件策略让你浏览器过于敏感了？反正代码是开源的，不放心就看看源代码或者自己搞个vs构建一下咯。

绝对是相信大佬的，可是我edge跟google都报毒下不了，rar文件野无法下载，不知道浏览器抽什么风

**Comment by NaughtDZ** [comment]
> 
> 绝对是相信大佬的，可是我edge跟google都报毒下不了，rar文件野无法下载，不知道浏览器抽什么风

直接右键链接复制到下载工具里，下不动也可以给下载工具设置个代理

**Comment by NaughtDZ** [comment]
额，实在不行，https://cowtransfer.com/s/e1cebddf4bdb49 点击链接查看 [ Image2Pdf_2.2.exe ] ，或访问奶牛快传 cowtransfer.com 输入传输口令 rh6i5u 查看；

**Comment by Aisakaguya** [comment]
大佬太猛了，现在可以转漫画了(´,,•ω•,,｀)♡
